version: '3.8'
services:
    web:
        build: .
        command: bash -c "dvc pull -r origin -f &&
                          pytest tests/unit_tests --html=experiments/unit_test/unit_tests_report.html &&
                          pytest tests/integration_tests --html=experiments/unit_test/integration_tests_report.html &&
                          python database/database.py --save --save_table_name train --save_csv_path data/train.csv &&
                          python database/database.py --save --save_table_name test --save_csv_path data/test.csv &&
                          python database/database.py --save --save_table_name predict --save_csv_path data/predict.csv &&
                          python database/database.py --load --load_table_name train --load_csv_path data/new_train.csv &&
                          python database/database.py --load --load_table_name test --load_csv_path data/new_test.csv &&
                          python database/database.py --load --load_table_name predict --load_csv_path data/new_predict.csv &&
                          python src/classifier.py --train data/new_train.csv --test data/new_test.csv --predict data/new_predict.csv --exp_name test1 &&
                          python database/database.py --delete --delete_table_name predict --save --save_table_name predict
                          --save_csv_path experiments/test1/predict_preds.csv"
        network_mode: "host"
        environment:
            - DB_IP=${DB_IP}
            - DB_PORT=${DB_PORT}
            - DB_NAME=${DB_NAME}
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - KAFKA_IP_PORT=${KAFKA_IP_PORT}
            - KAFKA_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
        image: pnthrleo/mle-template:latest
