name: CD

on:
  workflow_run:
    workflows: [CI]
    types:
      - completed

jobs:
  cd:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Pull with compose
        run: docker-compose pull
      -
        name: Install python
        uses: actions/setup-python@v4
        with:
            python-version: '3.9'
      -
        name: Setup Hashicorp Vault client
        run: pip install vault-cli
      - 
        name: Run Kafka
        run: vault-cli env --envvar kv/big_data_3/kafka -- docker compose -f kafka/docker-compose.yaml up -d
        env:
          VAULT_CLI_TOKEN: ${{ secrets.VAULT_CLI_TOKEN }}
          VAULT_CLI_URL: ${{ secrets.VAULT_CLI_URL }}
      -
        name: Run database
        run: vault-cli env --envvar kv/big_data_3/database -- docker compose -f database/docker-compose.yaml up -d
        env:
          VAULT_CLI_TOKEN: ${{ secrets.VAULT_CLI_TOKEN }}
          VAULT_CLI_URL: ${{ secrets.VAULT_CLI_URL }}
      -
        name: Sleep for 120 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '120s'
      -
        name: Run tests
        run: vault-cli env --envvar kv/big_data_3/app/db --envvar kv/big_data_3/app/kafka -- docker compose up --abort-on-container-exit
        env:
          VAULT_CLI_TOKEN: ${{ secrets.VAULT_CLI_TOKEN }}
          VAULT_CLI_URL: ${{ secrets.VAULT_CLI_URL }}
